### ISSUE TITLE
Co-include

### ISSUE THREAD

**Issue by qqwrv-f10eq** [Awsomedude/easyDialog#5]
I need to overwrite ShowPlayerDialog, but It not work if easyDialog include before CEFix.

And If not defined CE_AUTO must do nothing with ShowPlayerDialog.

CEFix include:
https://github.com/aktah/SAMP-CEFix/blob/master/CEFix.inc

Please help.

**Comment by Southclaws** [comment]
Hooking is always order-dependent so the only way to solve this is include order. I don't think there's anything that can be done in the source of this library that can solve your problem.

**Comment by qqwrv-f10eq** [comment]
I got it. Thanks !
